# Generated by Django 4.1.7 on 2023-04-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorys', to='core.category'),
        ),
        migrations.AddField(
            model_name='shop',
            name='ph_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='core.shop'),
        ),
    ]
