# Generated by Django 4.1.7 on 2023-04-11 03:11

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shop_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=None, upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
