# Generated by Django 4.1.7 on 2023-04-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_user_order_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderitems',
            new_name='products',
        ),
    ]
