# Generated by Django 4.1.7 on 2023-04-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitems_remove_order_orderid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderitems',
            new_name='orderitem',
        ),
    ]
